SELECT  CASE_DATA.CASE_KEY CASE_KEY_GAP,
        BEN_TYPES.BNTP_KEY BNTP_KEY_GAP,
        CDR_VIEW.MBGP_KEY_GAP MBGP_KEY_GAP,
        CASE_DATA.CONT_NO  SCHEME_NO_GAP,
        CASE_DATA.PLAN_NM  SCHEME_NM_GAP,
        BEN_TYPES.DESCRIPT  BEN_DESC_GAP,
        ------ START FIRST SECTION OF GAP TAB
        CDR_VIEW.BNTP_EFF_DT_GAP,
        TO_DATE(SCY708_BEN_LKUP.GET_BEOP_VALUE('COVG_ORIG_EFF_DATE_GAP',CASE_DATA.CASE_KEY,NULL,NULL,SYSDATE,'L'),'YYYY/MM/DD') COVG_ORIG_EFF_DATE_GAP,
        CDR_VIEW.ELGBL_PRSN_GAP,
        CDR_VIEW.ELGBL_PRSN2_GAP,
        SCY708_BEN_LKUP.GET_MBGP_DESC(CDR_VIEW.MBGP_KEY_GAP,CASE_DATA.CASE_KEY,CDR_VIEW.DUP_BEN_MBGP_GAP) MBR_GRP_DESC_GAP,
        CDR_VIEW.SLR_MBR_GRP_KEY_GAP,
        ENH_ELIG_RULES.MIN_HOURS MIN_PERIODIC_HRS_GAP,
        SCY708_BEN_LKUP.F_GET_PERIODIC_HRS_DEF(ENH_ELIG_RULES.SLRY_KEY) PERIODIC_HRS_DEF_GAP,
        SCY708_BEN_LKUP.GET_REF_CD_DESC(RISK_RULES.REL_TYP_CD,'RKRL REL TYP CD') THIS_IS_A_CELL_BEN_GAP, --this is a ____ benefit
        SCY708_BEN_LKUP.GET_REF_CD_DESC(RISK_RULES.PRRT_CD,'RKRL PRRT CD') BILL_PROR_METH_GAP,
        CDR_VIEW.DOMESTIC_PARTNER_GAP,
        ------ END FIRST SECTION OF GAP TAB
        ------ START SECOND SECTION OF GAB TAB
        ENH_ELIG_RTRNCH_ISS.MIN_SRVC_PRD  ISS_SRVC_RQT_GAP,
        SCY708_BEN_LKUP.GET_SVDF_DESC(ENH_ELIG_RTRNCH_ISS.SVDF_KEY)  ISS_SRVC_RQT_MOD_GAP,
        ENH_ELIG_RTRNCH_FUT.MIN_SRVC_PRD  FUT_SRVC_RQT_GAP,
        SCY708_BEN_LKUP.GET_SVDF_DESC(ENH_ELIG_RTRNCH_FUT.SVDF_KEY)  FUT_SRVC_RQT_MOD_GAP,
        DECODE(ENH_ELIG_RTRNCH_FUT.EDRL_KEY,NULL,'Immediate',EFF_DT_RULES.DESCRIPT) ENTRY_DT_GAP,
        CDR_VIEW.SPC_ENTRY_DT_GAP,
        SCY708_BEN_LKUP.F_GET_TERM_DT(CASE_DATA.CASE_KEY, CDR_VIEW.BNTP_KEY) TERM_DT_GAP,
        CDR_VIEW.SPC_TERM_DT_GAP,
        CDR_VIEW.TERM_DT_MODE_GAP,
        ----- END SECOND SECTION OF GAP TAB
        ----- START THIRD SECTION OF GAP TAB
        CDR_VIEW.INPATIENT_BNFT_GAP,
        CDR_VIEW.OUTPATIENT_BNFT_GAP,
        CDR_VIEW.PHYSICIAN_BNFT_GAP,
        CDR_VIEW.WELLNESS_BNFT_GAP,
        CDR_VIEW.BNFT_YEAR_GAP,
        --CENSUS AGE TYPE
        ---- END OF THIRD SECTION OF GAP TAB
--        FLAT_BNFT_AMT_GAP,
--        CDR_VIEW.BNFT_PCT_STD,
--        CDR_VIEW.STD_MAX_BNFT_STD,
--        CDR_VIEW.STD_MIN_BNFT_STD,
        ----- START OF FOURTH SECTION OF GAP TAB
        CDR_VIEW.STUDENT_AGE_GAP,
        SCY708_BEN_LKUP.F_GET_FREE_COVER_AMT(CDR_VIEW.CASE_KEY,BEN_TYPES.BNTP_KEY,SYSDATE,'N') FREE_COVER_GAP,
        CDR_VIEW.CNTRCT_TYPE_GAP,
        SCY708_BEN_LKUP.F_GET_SCHEME_LVL_BNTP_TYP(BEN_TYPES.BNTP_KEY) TRANSFER_GAP,
        
        CDR_VIEW.SERIES_GAP,
        
        SCY708_BEN_LKUP.F_GET_SLRY_CHG_DT(BEN_TYPES.BNTP_KEY,SYSDATE) SLRY_CHNG_DT_GAP, 
        ----- END OF THE FOURTH SECTION
        SCY708_BEN_LKUP.GET_CTRB_DESC(RISK_RULE_DETL.FDRT_KEY,SYSDATE) CONTRIB_GAP,
        CDR_VIEW.CONTRACT_PART_GAP,
        ----- START OF THE FIFTH SECTION
        
        CDR_VIEW.S125_PLAN_GAP,
        CDR_VIEW.S125_TAX_GAP,
        CDR_VIEW.EMP_CNTRB_TYP_GAP,
        
        
        SCB_BEN_LKUP.F_GET_COMMISSION_SCALE(CDR_VIEW.CASE_KEY,CDR_VIEW.BNTP_KEY,SYSDATE) COMM_SCALE_GAP,
        CDR_VIEW.BROKER_FEE_GAP,
        CDR_VIEW.SERVICE_FEE_GAP,
        ----- END OF THE FIFTH SECTION
        ----- START OF SIXTH SECTION
        CDR_VIEW.SOLAR_GRP_ID_GAP,
        CDR_VIEW.SOLAR_SCHED_SEQ_NUM_GAP,
        CDR_VIEW.SOLAR_SEQ_NUM_GAP,
        TO_DATE(CDR_VIEW.APP_SIG_DT_GAP,'YYYY/MM/DD') APP_SIG_DT_GAP,
        CDR_VIEW.PLAN_TYPE_ID_SUB_GAP,
        SCY708_BEN_LKUP.GET_PLAN_TYPE(BEN_TYPES.BNTP_KEY) PLAN_TYPE_GAP,
        CDR_VIEW.TPA_ALLOW_GAP,
        CDR_VIEW.RISK_GAP,
        CDR_VIEW.ACT_PARTIC_PCT_GAP,
        CDR_VIEW.RATE_GUAR_MO_GAP,
        CDR_VIEW.POOLING_CD_GAP,
        CDR_VIEW.RT_CHG_RSN_CD_GAP,
        CDR_VIEW.AGE_RATES_GAP,
        ----- END OF SIXTH SECTION
        CDR_VIEW.DUP_BEN_MBGP_GAP,
        CDR_VIEW.SL_RTNG_ADMIN_GAP
      FROM
        SCY908_BEN_GAP CDR_VIEW,
        CASE_DATA,
        BEN_TYPES,
        RISK_RULES,
        RISK_RULE_DETL,
        RISK_BEN_TRNCH,
        ENH_ELIG_RULES,
        EFF_DT_RULES,
        ENH_ELIG_RTRNCH ENH_ELIG_RTRNCH_ISS,
        ENH_ELIG_RTRNCH ENH_ELIG_RTRNCH_FUT
      WHERE
        CDR_VIEW.RPT_KEY = 22442
        AND CDR_VIEW.CASE_KEY = CASE_DATA.CASE_KEY
        AND CDR_VIEW.BNTP_KEY = BEN_TYPES.BNTP_KEY
        AND BEN_TYPES.BNTP_KEY = RISK_RULES.BNTP_KEY
        AND risk_rule_detl.rsk_shr_pct = 100
        AND RISK_RULE_DETL.EFF_DT <= SYSDATE
        AND (RISK_RULE_DETL.XPIR_DT >= SYSDATE OR RISK_RULE_DETL.XPIR_DT IS NULL)
        AND RISK_BEN_TRNCH.EFF_DT <= SYSDATE
        AND (RISK_BEN_TRNCH.XPIR_DT >= SYSDATE OR RISK_BEN_TRNCH.XPIR_DT IS NULL)
        AND RISK_RULES.RKRL_KEY = RISK_RULE_DETL.RKRL_KEY
        AND RISK_RULE_DETL.RKRL_KEY = RISK_BEN_TRNCH.RKRL_KEY
        AND RISK_BEN_TRNCH.RKRL_KEY = ENH_ELIG_RULES.RKRL_KEY
        AND ENH_ELIG_RULES.EERL_KEY = ENH_ELIG_RTRNCH_ISS.EERL_KEY
        AND ENH_ELIG_RTRNCH_ISS.GF_CD = '1'
        AND ENH_ELIG_RULES.EERL_KEY = ENH_ELIG_RTRNCH_FUT.EERL_KEY
        AND ENH_ELIG_RTRNCH_FUT.GF_CD = '0'
        AND ENH_ELIG_RTRNCH_FUT.EDRL_KEY = EFF_DT_RULES.EDRL_KEY(+)
        AND ENH_ELIG_RTRNCH_ISS.EFF_DT <= SYSDATE
        AND (ENH_ELIG_RTRNCH_ISS.XPIR_DT >= SYSDATE OR ENH_ELIG_RTRNCH_ISS.XPIR_DT IS NULL)
        AND ENH_ELIG_RTRNCH_FUT.EFF_DT <= SYSDATE
        AND (ENH_ELIG_RTRNCH_FUT.XPIR_DT >= SYSDATE OR ENH_ELIG_RTRNCH_FUT.XPIR_DT IS NULL)
      ORDER BY BEN_TYPES.SEQ_NUM;
