       SELECT
       BILL_GRP.DESCRIPT BILL_GRP_DESCRIPT_BILL_GRP
      ,ORG_INFO.ORGNAME_ORG ORG_NAME_BILLRL
      ,DECODE(PERSON_INFO.FIRSTNAME_PERSON,NULL,PERSON_INFO.FIRSTNAME_PERSON ||' '||PERSON_INFO.LASTNAME_PERSON,PERSON_INFO.FIRSTNAME_PERSON ||' '||PERSON_INFO.MIDNAME_PERSON||' '||PERSON_INFO.LASTNAME_PERSON) PERSON_NAME_BILLRL
      ,BILL_GRP_RULES.DESCRIPT BILL_RL_DESCRIPT_BILLRL
      ,bill_grp_rl_refs.bgrp_key BGRP_KEY_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDRDATA,NULL,ORG_INFO.LINE1_ADDRDATA,PERSON_INFO.LINE1_ADDRDATA) ADDR_LINE1_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDRDATA,NULL,ORG_INFO.LINE2_ADDRDATA,PERSON_INFO.LINE2_ADDRDATA) ADDR_LINE2_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDRDATA,NULL,ORG_INFO.LINE3_ADDRDATA,PERSON_INFO.LINE3_ADDRDATA) ADDR_LINE3_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDRDATA,NULL,DECODE(ORG_INFO.CITY_ADDRDATA||', '||ORG_INFO.STATE_ADDRDATA||' '||ORG_INFO.POSTCD_ADDRDATA,',  ',NULL,ORG_INFO.CITY_ADDRDATA
        ||', '||ORG_INFO.STATE_ADDRDATA||' '||ORG_INFO.POSTCD_ADDRDATA),DECODE(PERSON_INFO.CITY_ADDRDATA||', '||PERSON_INFO.STATE_ADDRDATA||' '||
        PERSON_INFO.POSTCD_ADDRDATA,',  ',NULL,PERSON_INFO.CITY_ADDRDATA||', '||PERSON_INFO.STATE_ADDRDATA||' '||PERSON_INFO.POSTCD_ADDRDATA)) CITY_STATE_ZIP_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDRPHONE_P1,NULL,DECODE(ORG_INFO.PHONEEXT_ADDRPHONE_O1,NULL,ORG_INFO.PHONENUM_ADDRPHONE_O1 ,ORG_INFO.PHONENUM_ADDRPHONE_O1||' ext.'||
      ORG_INFO.PHONEEXT_ADDRPHONE_O1),DECODE(PERSON_INFO.PHONEEXT_ADDRPHONE_P1,NULL,PERSON_INFO.PHONENUM_ADDRPHONE_P1 ,PERSON_INFO.PHONENUM_ADDRPHONE_P1||' ext.'||PERSON_INFO.PHONEEXT_ADDRPHONE_P1))  PHONE_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDRPHONE_P2,NULL,DECODE(ORG_INFO.PHONEEXT_ADDRPHONE_O2,NULL,ORG_INFO.PHONENUM_ADDRPHONE_O2 ,ORG_INFO.PHONENUM_ADDRPHONE_O2||' ext.'||
      ORG_INFO.PHONEEXT_ADDRPHONE_O2),DECODE(PERSON_INFO.PHONEEXT_ADDRPHONE_P2,NULL,PERSON_INFO.PHONENUM_ADDRPHONE_P2 ,PERSON_INFO.PHONENUM_ADDRPHONE_P2||' ext.'||PERSON_INFO.PHONEEXT_ADDRPHONE_P2))  FAX_BILLRL
      ,DECODE(PERSON_INFO.ADDRID_ADDROTHER,NULL,ORG_INFO.EMAILDATA_ADDROTHER,PERSON_INFO.EMAILDATA_ADDROTHER) EMAIL_BILLRL
      ,PAYER_REF2.PAYEE_NM PAYEE_NM_BILLRL
      ,PERSON_INFO.PROF_CD_MISC_CONTACTS CONTACT_TITLE_BILLRL
      ,DECODE(PERSON_INFO.CONTACT_TYP_CD_MISC_CONTACTS,NULL,SCY708_BEN_LKUP.GET_REF_CD_DESC(ORG_INFO.CONTACT_TYP_CD_MISC_CONTACTS,'MSCT CONTACT TYP CD'),
       SCY708_BEN_LKUP.GET_REF_CD_DESC(PERSON_INFO.CONTACT_TYP_CD_MISC_CONTACTS,'MSCT CONTACT TYP CD')) CONTACT_TYPE_BILLRL
      FROM
        BILL_GRP
        ,BILL_GRP_STAT
        ,BILL_GRP_RULES
        ,BILL_GRP_RL_REFS
        ,PAYER_REF PAYER_REF1
        ,PAYER_REF PAYER_REF2
        ,CASE_UNALL_ACCT
        ,PARTYXREF PARTYXREF1
        ,(SELECT
            PARTYXREF1.NAMEID	NAMEID_PARTYXREF1,
            PARTYXREF1.REFKEY	REFKEY_PARTYXREF1,
            PARTYXREF1.REFTYPE	REFTYPE_PARTYXREF1,
            PERSON.NAMEID	NAMEID_PERSON,
            PERSON.FIRSTNAME	FIRSTNAME_PERSON,
            PERSON.MIDNAME MIDNAME_PERSON,
            PERSON.LASTNAME	LASTNAME_PERSON,
            ADDRDATA_P.ADDRDATAID	ADDRDATAID_ADDRDATA,
            ADDRDATA_P.ADDRID	ADDRID_ADDRDATA,
            ADDRDATA_P.ADDRTYPE	ADDRTYPE_ADDRDATA,
            ADDRDATA_P.CITY	CITY_ADDRDATA,
            ADDRDATA_P.COUNTRY	COUNTRY_ADDRDATA,
            ADDRDATA_P.EFFECTDT	EFFECTDT_ADDRDATA,
            ADDRDATA_P.LINE1	LINE1_ADDRDATA,
            ADDRDATA_P.LINE2	LINE2_ADDRDATA,
            ADDRDATA_P.LINE3	LINE3_ADDRDATA,
            ADDRDATA_P.POSTCD	POSTCD_ADDRDATA,
            ADDRDATA_P.STATE	STATE_ADDRDATA,
            ADDRDATA_P.XPIRDT	XPIRDT_ADDRDATA,
            MISC_CONTACTS_P.PROF_CD	PROF_CD_MISC_CONTACTS,
            MISC_CONTACTS_P.XPIR_DT	XPIR_DT_MISC_CONTACTS,
            MISC_CONTACTS_P.MSCT_KEY	MSCT_KEY_MISC_CONTACTS,
            MISC_CONTACTS_P.CONTACT_TYP_CD	CONTACT_TYP_CD_MISC_CONTACTS,
            MISC_CONTACTS_P.DESCRIPT	DESCRIPT_MISC_CONTACTS,
            MISC_CONTACTS_P.EFF_DT	EFF_DT_MISC_CONTACTS,
            MISC_CONTACTS_P.PRIM_CONTACT_CD	PRIM_CONTACT_CD_MISC_CONTACTS,
            MISC_CONTACTS_P.REF_KEY	REF_KEY_MISC_CONTACTS,
            MISC_CONTACTS_P.REF_TYP_CD	REF_TYP_CD_MISC_CONTACTS,
            ADDROTHER_P.ADDRID ADDRID_ADDROTHER,
            ADDROTHER_P.EMAILDATA EMAILDATA_ADDROTHER,
            ADDRPHONE_P1.ADDRID ADDRID_ADDRPHONE_P1,
            ADDRPHONE_P1.PHONEEXT PHONEEXT_ADDRPHONE_P1,
            ADDRPHONE_P1.PHONENUM PHONENUM_ADDRPHONE_P1,
            ADDRPHONE_P2.ADDRID ADDRID_ADDRPHONE_P2,
            ADDRPHONE_P2.PHONEEXT PHONEEXT_ADDRPHONE_P2,
            ADDRPHONE_P2.PHONENUM PHONENUM_ADDRPHONE_P2
          FROM
            PARTYXREF PARTYXREF1
            ,PARTYXREF PARTYXREF_P2
            ,PARTYXREF PARTYXREF_P3
            ,MISC_CONTACTS MISC_CONTACTS_P
            ,PARTY PARTY_P
            ,PERSON
            ,ADDRDATA ADDRDATA_P
            ,ADDRPHONE ADDRPHONE_P1
            ,ADDRPHONE ADDRPHONE_P2
            ,ADDROTHER ADDROTHER_P
          WHERE
            PARTYXREF1.REFTYPE = 'PAYR'
            AND PARTYXREF1.REFKEY = MISC_CONTACTS_P.REF_KEY
            AND MISC_CONTACTS_P.REF_TYP_CD = 'PAYR'
            AND MISC_CONTACTS_P.MSCT_KEY = PARTYXREF_P2.REFKEY
            AND NVL(MISC_CONTACTS_P.EFF_DT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
            AND NVL(MISC_CONTACTS_P.XPIR_DT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
            AND PARTYXREF_P2.REFTYPE = 'MSCT'
            AND PARTYXREF_P2.NAMEID = PARTY_P.NAMEID
            AND PARTY_P.PARTYTYPE = 'P'
            AND PARTY_P.NAMEID = PERSON.NAMEID
            AND PERSON.NAMEID = PARTYXREF_P3.NAMEID
            AND PARTYXREF_P3.REFTYPE = 'COMM'
            AND PARTYXREF_P3.REFKEY = ADDRDATA_P.ADDRID(+)
            AND ADDRDATA_P.addrtype(+) = '1' --BH15515 10/19/2005
            AND NVL(ADDRDATA_P.EFFECTDT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
            AND NVL(ADDRDATA_P.XPIRDT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
            AND ADDRPHONE_P1.PHONETYPE(+) = '02'--TYPE 02 IS PHONE
            AND NVL(ADDRPHONE_P1.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDRPHONE_P1.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            AND PARTYXREF_P3.REFKEY = ADDRPHONE_P2.ADDRID(+)
            AND ADDRPHONE_P2.PHONETYPE(+) = '03' --TYPE 03 IS FAX
            AND NVL(ADDRPHONE_P2.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDRPHONE_P2.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            AND PARTYXREF_P3.REFKEY = ADDRPHONE_P1.ADDRID(+)
            AND PARTYXREF_P3.REFKEY = ADDROTHER_P.ADDRID(+)
            AND NVL(ADDROTHER_P.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDROTHER_P.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            AND PARTYXREF_P3.REFKEY = ADDRDATA_P.ADDRID(+)
            AND NVL(ADDRDATA_P.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDRDATA_P.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            ) PERSON_INFO
        ,(SELECT
            PARTYXREF1.NAMEID	NAMEID_PARTYXREF1,
            PARTYXREF1.REFKEY	REFKEY_PARTYXREF1,
            PARTYXREF1.REFTYPE	REFTYPE_PARTYXREF1,
            ORGANIZATION.NAMEID	NAMEID_ORG,
            ORGANIZATION.ORGNAME	ORGNAME_ORG,
            ADDRDATA_O.ADDRDATAID	ADDRDATAID_ADDRDATA,
            ADDRDATA_O.ADDRID	ADDRID_ADDRDATA,
            ADDRDATA_O.ADDRTYPE	ADDRTYPE_ADDRDATA,
            ADDRDATA_O.CITY	CITY_ADDRDATA,
            ADDRDATA_O.COUNTRY	COUNTRY_ADDRDATA,
            ADDRDATA_O.EFFECTDT	EFFECTDT_ADDRDATA,
            ADDRDATA_O.LINE1	LINE1_ADDRDATA,
            ADDRDATA_O.LINE2	LINE2_ADDRDATA,
            ADDRDATA_O.LINE3	LINE3_ADDRDATA,
            ADDRDATA_O.POSTCD	POSTCD_ADDRDATA,
            ADDRDATA_O.STATE	STATE_ADDRDATA,
            ADDRDATA_O.XPIRDT	XPIRDT_ADDRDATA,
            MISC_CONTACTS_O.PROF_CD	PROF_CD_MISC_CONTACTS,
            MISC_CONTACTS_O.XPIR_DT	XPIR_DT_MISC_CONTACTS,
            MISC_CONTACTS_O.MSCT_KEY	MSCT_KEY_MISC_CONTACTS,
            MISC_CONTACTS_O.CONTACT_TYP_CD	CONTACT_TYP_CD_MISC_CONTACTS,
            MISC_CONTACTS_O.DESCRIPT	DESCRIPT_MISC_CONTACTS,
            MISC_CONTACTS_O.EFF_DT	EFF_DT_MISC_CONTACTS,
            MISC_CONTACTS_O.PRIM_CONTACT_CD	PRIM_CONTACT_CD_MISC_CONTACTS,
            MISC_CONTACTS_O.REF_KEY	REF_KEY_MISC_CONTACTS,
            MISC_CONTACTS_O.REF_TYP_CD	REF_TYP_CD_MISC_CONTACTS,
            ADDROTHER_O.ADDRID ADDRID_ADDROTHER,
            ADDROTHER_O.EMAILDATA EMAILDATA_ADDROTHER,
            ADDRPHONE_O1.ADDRID ADDRID_ADDRPHONE_O1,
            ADDRPHONE_O1.PHONEEXT PHONEEXT_ADDRPHONE_O1,
            ADDRPHONE_O1.PHONENUM PHONENUM_ADDRPHONE_O1,
            ADDRPHONE_O2.ADDRID ADDRID_ADDRPHONE_O2,
            ADDRPHONE_O2.PHONEEXT PHONEEXT_ADDRPHONE_O2,
            ADDRPHONE_O2.PHONENUM PHONENUM_ADDRPHONE_O2
          FROM
            PARTYXREF PARTYXREF1
            ,PARTYXREF PARTYXREF_O2
            ,PARTYXREF PARTYXREF_O3
            ,MISC_CONTACTS MISC_CONTACTS_O
            ,PARTY PARTY_O
            ,ORGANIZATION
            ,ADDRDATA ADDRDATA_O
            ,ADDRPHONE ADDRPHONE_O1
            ,ADDRPHONE ADDRPHONE_O2
            ,ADDROTHER ADDROTHER_O
          WHERE
            PARTYXREF1.REFTYPE = 'PAYR'
            AND PARTYXREF1.REFKEY = MISC_CONTACTS_O.REF_KEY
            AND MISC_CONTACTS_O.REF_TYP_CD = 'PAYR'
            AND MISC_CONTACTS_O.MSCT_KEY = PARTYXREF_O2.REFKEY
            AND NVL(MISC_CONTACTS_O.EFF_DT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
            AND NVL(MISC_CONTACTS_O.XPIR_DT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
            AND PARTYXREF_O2.REFTYPE = 'MSCT'
            AND PARTYXREF_O2.NAMEID = PARTY_O.NAMEID
            AND PARTY_O.PARTYTYPE = 'O'
            AND PARTY_O.NAMEID = ORGANIZATION.NAMEID
            AND ORGANIZATION.NAMEID = PARTYXREF_O3.NAMEID
            AND PARTYXREF_O3.REFTYPE = 'COMM'
            AND PARTYXREF_O3.REFKEY = ADDRDATA_O.ADDRID(+)
            AND ADDRDATA_O.addrtype(+) = '1' --BH15515 10/19/2005
            AND NVL(ADDRDATA_O.EFFECTDT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
            AND NVL(ADDRDATA_O.XPIRDT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
            AND PARTYXREF_O3.REFKEY = ADDRPHONE_O2.ADDRID(+)
            AND ADDRPHONE_O2.PHONETYPE(+) = '03' --TYPE 03 IS FAX
            AND NVL(ADDRPHONE_O2.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDRPHONE_O2.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            AND PARTYXREF_O3.REFKEY = ADDRPHONE_O1.ADDRID(+)
            AND ADDRPHONE_O1.PHONETYPE(+) = '02'--TYPE 02 IS PHONE
            AND NVL(ADDRPHONE_O1.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDRPHONE_O1.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            AND PARTYXREF_O3.REFKEY = ADDROTHER_O.ADDRID(+)
            AND NVL(ADDROTHER_O.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDROTHER_O.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            AND PARTYXREF_O3.REFKEY = ADDRDATA_O.ADDRID(+)
            AND NVL(ADDRDATA_O.EFFECTDT(+),'01/01/1905') <= N_REQUEST_DT_IN
            AND NVL(ADDRDATA_O.XPIRDT(+),'01/01/3005') >= N_REQUEST_DT_IN
            ) ORG_INFO
        WHERE
          BILL_GRP.CASE_KEY = N_CASE_KEY_IN
          AND BILL_GRP.BGRP_KEY = BILL_GRP_STAT.BGRP_KEY
          AND BILL_GRP_STAT.STAT_CD = '00'
          AND BILL_GRP_STAT.EFF_DT <= N_REQUEST_DT_IN
          AND (BILL_GRP_STAT.XPIR_DT >= N_REQUEST_DT_IN OR BILL_GRP_STAT.XPIR_DT IS NULL)
          AND BILL_GRP_RL_REFS.BGRP_KEY = BILL_GRP.BGRP_KEY
          AND BILL_GRP_RL_REFS.BGRL_KEY = BILL_GRP_RULES.BGRL_KEY
          AND NVL(BILL_GRP_RULES.EFF_DT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
          AND NVL(BILL_GRP_RULES.XPIR_DT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
          AND NVL(BILL_GRP_RL_REFS.EFF_DT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
          AND NVL(BILL_GRP_RL_REFS.XPIR_DT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
          AND BILL_GRP_RL_REFS.BGRR_KEY = PAYER_REF1.BGRR_KEY
          AND NVL(PAYER_REF1.EFF_DT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
          AND NVL(PAYER_REF1.XPIR_DT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
          AND PAYER_REF1.PAYR_KEY = PAYER_REF2.PAYR_KEY
          AND PAYER_REF2.REF_KEY = CASE_UNALL_ACCT.CSUA_KEY
          AND BILL_GRP.CASE_KEY = CASE_UNALL_ACCT.CASE_KEY
          AND PAYER_REF2.PAYEE_NM IS NOT NULL
          AND PAYER_REF2.REF_TYP_CD = 'CSUA'
          AND NVL(PAYER_REF2.EFF_DT(+),to_date('01/01/1905','MM/DD/YYYY')) <= N_REQUEST_DT_IN
          AND NVL(PAYER_REF2.XPIR_DT(+),to_date('01/01/3005','MM/DD/YYYY')) >= N_REQUEST_DT_IN
          AND PAYER_REF2.PAYR_KEY = PARTYXREF1.REFKEY
          AND PARTYXREF1.REFTYPE = 'PAYR'
          and PARTYXREF1.REFKEY = ORG_INFO.refkey_partyxref1
          and PARTYXREF1.REFKEY = person_info.refkey_partyxref1(+);
